

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <groupId>com.prince.gmail</groupId>
 <artifactId>spring_gmail_service</artifactId>
 <version>0.0.1-SNAPSHOT</version>
 <packaging>war</packaging>
 <name>gmail</name>
 <description>gmail implementation</description>
 <properties>
 <maven.compiler.source>21</maven.compiler.source>
 <maven.compiler.target>21</maven.compiler.target>
 <spring.version>6.1.6</spring.version>
 </properties>
 <dependencies>
 <!--Spring mvc-->
 <dependency>
 <groupId>org.springframework</groupId>
 <artifactId>spring-webmvc</artifactId>
 <version>${spring.version}</version>
 </dependency>
 <!--JSTL -->
 <dependency>
 <groupId>jakarta.servlet.jsp.jstl</groupId>
 <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
 <version>3.0.0</version>
 </dependency>
   <!--Jakarta jsp-->
 <dependency>
 <groupId>jakarta.servlet.jsp</groupId>
 <artifactId>jakarta.servlet.jsp-api</artifactId>
 <version>3.1.1</version>
 <scope>provided</scope>
 </dependency>
 <dependency>
 <groupId>org.glassfish.web</groupId>
 <artifactId>jakarta.servlet.jsp.jstl</artifactId>
 <version>3.0.1</version>
 </dependency>
 <!--Servlet api -->
 <dependency>
 <groupId>jakarta.servlet</groupId>
 <artifactId>jakarta.servlet-api</artifactId>
 <version>6.0.0</version>
 <scope>provided</scope>
 </dependency>
<!--Spring mail -->
 <dependency>
 <groupId>org.springframework</groupId>
 <artifactId>spring-context-support</artifactId>
 <version>${spring.version}</version>
 </dependency>
 <!--Jakarta mail -->
<dependency>
<groupId>com.sun.mail</groupId>
<artifactId>jakarta.mail</artifactId>
<version>2.0.1</version>
</dependency>
 </dependencies>
   <build>
   <finalName>spring-gmail-service</finalName>
 <plugins>
 	<plugin>
 		<artifactId>maven-war-plugin</artifactId>
 		<version>3.4.0</version>
 	</plugin>
 </plugins>
 </build>
</project>